Add documentation for Component Translations
neoforged/Documentation pull request #143
Opened 2024-08-01 20:54 UTC by BasiqueEvangelist

Adds documentation for the changed done by neoforged/NeoForge#1134

2024-08-01 21:47 UTC, ChampionAsh5357 requested changes
Thanks for the contribution!

This requires a lot more description. It currently reads like a passing statement, which does not help me understand what this feature is and how to use it effectively. Also, you should mention the version this feature was added since it was a 1.21 release change.

2024-08-01 21:47 UTC, ChampionAsh5357 commented on docs/resources/client/i18n.md
> +### Component Translations
This title is kind of misleading since what this is providing is a rich component format for translations within the lang file.

2024-08-01 21:47 UTC, ChampionAsh5357 commented on docs/resources/client/i18n.md
> +NeoForge extends the vanilla language file format to allow using arrays of `Component`s in translations.
Using components at all instead of just a translatable string I assume.

2024-08-01 21:47 UTC, ChampionAsh5357 commented on docs/resources/client/i18n.md
> +an argument from the surrounding translation.
This is not explained at all and I have no idea what it does from such a brief explanation.

2024-08-01 21:47 UTC, ChampionAsh5357 commented on docs/resources/client/i18n.md
> +{
Probably should mention in `/lang/en_us.json`

2024-08-01 21:47 UTC, ChampionAsh5357 commented on docs/resources/client/i18n.md
> +    "",
The first element is the parent component. All other components are siblings to the parent. That does not mean the parent component needs to be empty. It just means that any styles applies will trickle down to the siblings.

2024-08-01 21:47 UTC, ChampionAsh5357 commented on docs/resources/client/i18n.md
> +    {"text": "A mysterious stranger known only as <", "color": "gray"},
I'm guessing this is a literal component. It's not obviously clear.

2024-08-01 21:47 UTC, ChampionAsh5357 commented on docs/resources/client/i18n.md
> +    {"index": 0, "obfuscated": true},
This is also not clear that it refers to the arguments provided by the translation, especially since those were 1-indexed.

2024-08-01 21:47 UTC, ChampionAsh5357 commented on docs/resources/client/i18n.md
> +For example, you can modify the Vanilla chat format like so:
You should probably show the Java equivalent and say 'For example, we can take this complex component <java here> and represent it as a JSON using <json here>' or something similar.

2024-08-01 21:47 UTC, ChampionAsh5357 commented on docs/resources/client/i18n.md
> +![The above translation in-game](/img/component_translations_example.png)
On my first look, it was not obviously clear what each part in this image represented in the text.

2024-10-23 21:07 UTC, closed without merging

2024-10-23 23:40 UTC, tmvkrpxl0 commented
This reminds me of component documentation I've written a while ago.
@ChampionAsh5357 btw why was it gone?

2024-10-24 02:12 UTC, ChampionAsh5357 commented
I'm going to need more information than it's gone. Afaik, it's still there, unless you're talking about something specific.

2024-10-28 02:17 UTC, tmvkrpxl0 commented
Oh it's just merged into i18n