Update docs for capability rework
neoforged/Documentation pull request #34
Opened 2023-12-07 23:42 UTC by Technici4n

Mostly adapted from the blog post, but keeping some of the old content where that made sense.

Beyond the two main changed files, I also fixed references to capabilities elsewhere. Some of the other pages will still need an update, but at least everything related to caps should be clean now.

2023-12-08 14:58 UTC, ChampionAsh5357 requested changes
Bunch of general questions because my lack of understanding of the underlying system. I have avoided commenting on syntax changes as much as possible as per your request. They will be addressed at a later point in time since they don't affect the user experience.

2023-12-08 14:58 UTC, ChampionAsh5357 commented on docs/datastorage/attachments.md
> +- a default value supplier to create the instance when the data is first accessed, or to compare stacks that have the data and stacks that don't have it;
Is this only true for stacks, or does it apply to any attached object?

2023-12-08 14:58 UTC, ChampionAsh5357 commented on docs/datastorage/attachments.md
> +- additional configuration options for the attachment, for example the `copyOnDeath` flag.
This probably should be explained more since these additional configurations require the serializer to be present.

2023-12-08 14:58 UTC, ChampionAsh5357 commented on docs/datastorage/attachments.md
> +(This can be intended).
This is a weird way of just saying 'If you don't want your attachment to persist its data, do not provide a serializer.'

2023-12-08 14:58 UTC, ChampionAsh5357 commented on docs/datastorage/attachments.md
> +There are a few ways to provide an attachment serializer: directly implementing `IAttachmentSerializer`, implementing `INBTSerializable` and using the static `AttachmentSerializer.serializable()` met
Latter option should be explicitly stated in a warning.

2023-12-08 14:58 UTC, ChampionAsh5357 commented on docs/datastorage/attachments.md
> +In any case, we recommend using a `DeferredRegister` for registration:
This line isn't really necessary. It's more important to state that attachment types must be registered.

2023-12-08 14:58 UTC, ChampionAsh5357 commented on docs/datastorage/attachments.md
> +ATTACHMENT_TYPES.register(modBus);
Comment here saying to add it within the mod's constructor.

2023-12-08 14:58 UTC, ChampionAsh5357 commented on docs/datastorage/attachments.md
> +```
This should probably be in an important block since it could otherwise be glossed over.

2023-12-08 14:58 UTC, ChampionAsh5357 commented on docs/datastorage/attachments.md
> +Currently, only serializable item stack attachments are synced with the client.
Does this also fix the bug with item stack in the creative menu involving the weirdness when an attachment is present on the client and needs to be synced back to the server?

2023-12-08 14:58 UTC, ChampionAsh5357 commented on docs/datastorage/attachments.md
> +To sync block entity, chunk, or entity attachments, you need to [send a packet to the client][network] yourself.
Just for confirmation, these can be sent any time the attachment is accessed?

2023-12-08 14:58 UTC, ChampionAsh5357 commented on docs/datastorage/attachments.md
> +More complex handling can be implemented via `PlayerEvent.Clone` by reading the data from the original entity and assigning it to the new entity. In this event, the `#isWasDeath` method can be used t
Example should be provided here.

2023-12-08 14:58 UTC, ChampionAsh5357 commented on docs/datastorage/capabilities.md
> +See `CapabilityHooks` for a list of the providers registered by NeoForge itself.
Link!

2023-12-08 14:58 UTC, ChampionAsh5357 commented on docs/datastorage/capabilities.md
> +register your `RegisterCapabilitiesEvent` handler with a higher priority.
When would this matter?

2023-12-08 15:11 UTC, Technici4n commented on docs/datastorage/capabilities.md
> +Invalidation is exclusive to block capabilities. Entity and item stack capabilities do not need to be invalidated.
For entities and items, the cap is only valid right after the query and should not be cached

2023-12-08 15:12 UTC, Technici4n commented on docs/datastorage/capabilities.md
> +## Block capability caching
This is not written on the page but the cache will not query unloaded chunks. Of course, once the chunk loads the cache will receive a notification and try to query again. Not sure if that answers the question?

2023-12-08 15:13 UTC, Technici4n commented on docs/datastorage/capabilities.md
> +- If the configuration of a capability-providing block entity changes.
In the sense of a machine configuration changing in such a way that previously returned capabilities are no longer valid, or that new capabilities have become available. Configuration isn't the clearest yeah

2023-12-08 15:54 UTC, ChampionAsh5357 commented on docs/datastorage/attachments.md
> +More complex handling can be implemented via `PlayerEvent.Clone` by reading the data from the original entity and assigning it to the new entity. In this event, the `#isWasDeath` method can be used t
I think it's a good idea to have if someone has such a use case. The documentation is meant to be for people who are beginners or experienced modders, so if we mention something, we should have any corollaries necessary.

2023-12-08 16:40 UTC, Technici4n commented on docs/datastorage/capabilities.md
> +## Block capability caching
On the next query.

2023-12-11 15:22 UTC, ChampionAsh5357 approved these changes
Good enough, any formatting errors can be addressed in a future commit. @XFactHD and @Matyrobbrt, will give you until whenever Thursday to do any additional reviews or comments.

2023-12-15 15:58 UTC, XFactHD commented
Looks good to me overall, just a few minor points
- It might be worth mentioning that the fluid capability for items is slightly special due to the way buckets hold fluids
- The remark regarding why block caps are looked up from the level now should explicitly mention why (i.e. that blocks without BEs can have caps now as well)
- If the holder of a data attachment requires it, is it automatically marked dirty when a non-existent attachment is retrieved and therefore default-initialized?

Other than that: :shipit:

2023-12-21 14:30 UTC, XFactHD approved these changes

2023-12-21 14:45 UTC, merged