Fix example code in networking docs
neoforged/Documentation pull request #43
Opened 2024-01-01 13:29 UTC by TBoshoven

This snippet referred to a class that doesn't exist

2024-01-01 14:02 UTC, Matyrobbrt requested changes

2024-01-01 14:02 UTC, Matyrobbrt commented on docs/networking/payload.md
>  public static void register(final RegisterPacketHandlerEvent event) {
You've missed a spot

2024-01-04 15:23 UTC, IchHabeHunger54 approved these changes

2024-01-04 18:18 UTC, Matyrobbrt approved these changes

2024-01-04 18:18 UTC, merged