Update the conditions page
neoforged/Documentation pull request #55
Opened 2024-02-19 12:42 UTC by Matyrobbrt

Update the conditions page to the new keys and the neo mod id and add an example.

2024-02-19 17:36 UTC, IchHabeHunger54 requested changes
Fine overall, just one request.

2024-02-19 17:36 UTC, IchHabeHunger54 commented on docs/resources/server/conditional.md
>  Implementations
If you're already changing this page, please migrate to # and ## for h1s and h2s.

2024-02-21 15:27 UTC, IchHabeHunger54 approved these changes

2024-02-22 15:43 UTC, ChampionAsh5357 approved these changes

2024-02-22 19:23 UTC, XFactHD approved these changes

2024-02-22 19:23 UTC, merged