Add 1.20 changes
neoforged/Documentation pull request #6
Opened 2023-07-28 21:13 UTC by Matyrobbrt

The 1.20 changes were overwritten by me when messing around with versioning while porting to Docusaurus. This PR adds them back.

2023-07-29 08:14 UTC, marchermans approved these changes

2023-08-01 11:05 UTC, sciwhiz12 requested changes

2023-08-01 11:05 UTC, sciwhiz12 commented on docs/blocks/index.md
> +In the past there have been several mods that have allowed users to disable blocks/items in a configuration file. However, you shouldn't do this. There is no limit on the amount of blocks that can be
`[creativetabs]` links needs to be updated. Matching upstream: [MinecraftForge/Documentation@`1.19.x...1.20.x`#diff-9b91547ac8](https://github.com/MinecraftForge/Documentation/compare/1.19.x...1.20.x#diff-9b91547ac8a61a49f08bca4e44988b3f80080288c9ccb2ed5a18a0abc2a475c1R47).

2023-08-01 11:05 UTC, sciwhiz12 commented on docs/resources/server/advancements.md
> +      return new ExampleTriggerInstance(player, item);
Too much added intentation: existing was 2 spaces, you added 4 for a total of 6.
```suggestion
    return new ExampleTriggerInstance(player, item);
```

2023-08-01 13:21 UTC, sciwhiz12 requested changes

2023-08-01 13:21 UTC, sciwhiz12 commented on docs/resources/server/advancements.md
> +    return new ExampleTriggerInstance(player, item);
I just realized, the indentation in the rest of the examples use 2 space. Go back, go back!
```suggestion
  return new ExampleTriggerInstance(player, item);
```

2023-08-01 13:27 UTC, sciwhiz12 approved these changes

2023-08-01 13:28 UTC, merged