Update to NG7
neoforged/Documentation pull request #68
Opened 2024-05-13 20:04 UTC by ChampionAsh5357

Supersedes #54 

Updates the documentation to reflect the changes made in NG7.

2024-05-13 20:11 UTC, marchermans commented
![image](https://github.com/neoforged/Documentation/assets/5585406/0af5f1af-d57e-4165-9986-d9f500ed6b61)
Typo in the version.

2024-05-13 21:36 UTC, ChampionAsh5357 commented
Fixed hopefully.

2024-05-13 22:51 UTC, IchHabeHunger54 requested changes
A few rephrasings, otherwise looking good. I am not familiar with NeoGradle in any way, this was purely a "does this sound like English?" kind of review.

It might be worth explaining what Parchment does in a bit more detail. Most notably, it should be pointed out that applying Parchment to an existing project will not cause problems because parameter names (and javadocs) are ignored by the JVM, and will thus only impact development after it has been included in the project. A link to the Parchment contribution page might also be a good idea.

2024-05-13 22:51 UTC, IchHabeHunger54 commented on neogradle/docs/configuration/index.mdx
> +Access Transformers can widen the visibility or modify the `final` flag of Minecraft classes, methods, and fields.
Link to AT article.

2024-05-13 22:51 UTC, IchHabeHunger54 commented on neogradle/docs/configuration/runs.md
> +Run configurations define how an instance of the game is going to run. This includes arguments, working directories, task names, etc. Run configurations are defined within the `runs` block. While no
```suggestion
Run configurations define how an instance of the game is going to run. This includes arguments, working directories, task names, etc. Run configurations are defined within the `runs` block. No runs are configured by default, however NeoGradle provides the configurations `client`, `server`, `data` and `gameTestServer` out of the box.
```

2024-05-13 22:51 UTC, IchHabeHunger54 commented on neogradle/docs/index.md
> +While you can use version ranges for the NeoGradle plugin, it is not recommended to do so, as that may lead to more frequent decompilation and recompilation rounds and possible behavioral changes.
Copypasta?

2024-05-13 22:51 UTC, IchHabeHunger54 commented on neogradle/docs/parchment.md
> +[Parchment] is a community-sourced set of mappings of *parameter names* and *javadocs* that augment the official names released by Mojang. By using parchment, you can get parameter names for most Min
Not a fan of the cursive, consider using bold (**) instead.

2024-05-14 17:22 UTC, IchHabeHunger54 approved these changes

2024-05-14 20:33 UTC, merged